language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    php: hhvm

before_script:
  - php bin/vendors.php
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit --coverage-text --coverage-clover=coverage.clover


